In [12]:
import cv2
import numpy as np

img = cv2.imread('data/building.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 200, apertureSize = 3)
clone_img = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

minLineLength = 30
maxLineGap = 10

'''
lines = cv2.HoughLines(edges, 1, np.pi/180, 100)
for rho, theta in lines[0]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))

    cv2.line(img, (x1, y1), (x2, y2), (0, 0, 255), 3)
    cv2.line(clone_img, (x1, y1), (x2, y2), (0, 255, 0), 3)
'''

lines = cv2.HoughLinesP(edges, 1, np.pi/180, 80, minLineLength, maxLineGap)
for x in range(0, len(lines)):
    for x1, y1, x2, y2 in lines[x]:
        cv2.line(img, (x1, y1), (x2, y2), (0, 255, 0), 3)
        cv2.line(clone_img, (x1, y1), (x2, y2), (0, 255, 0), 3)

print lines

cv2.imwrite('data/houghlines3.jpg', img)
cv2.imwrite('data/houghlines3_clone.jpg', clone_img)

[[[681  96 694  90]]

 [[657 106 677  98]]

 [[768  59 779  54]]

 ..., 
 [[503 391 514 391]]

 [[299 112 299 100]]

 [[185 286 185 271]]]


True